---
- hosts: all
  become: yes
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: update
      apt:
        update_cache: yes
    - name: update and upgrade all packages
      apt:
        name: "*"
        state: latest
    - name: install base apps
      become: yes
      apt:
        name:
          - build-essential
          - ca-certificates
          - cmake
          - cmatrix
          - curl
          - gettext
          - gnupg
          - htop
          - nala
          - neofetch
          - lsb-release
          - tmux
          - unzip
          - wget
          - zsh
        state: latest
    - name: copy sshd_config file
      become: yes
      file:
        src: ~/git/dotFiles/ssh/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: find 16 fastest repositories
      become: yes
      ansible.builtin.shell: nala fetch --auto --fetches 16
      become: true
    - name: nala update
      become: yes
      ansible.builtin.shell: nala update
      become: true
