---
- hosts: all
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: install base apps
      apt:
        name:
          - build-essential
          - ca-certificates
          - cmake
          - cmatrix
          - gettext
          - gnupg
          - htop
          - neofetch
          - lsb-release
          - lsd
          - sudo
          - tmux
          - unzip
          - zsh
        state: latest
    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: add user zyzyx
      ansible.builtin.user:
        name: james
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: add ssh key
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
