---
- hosts: all
  become: yes
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: update
      apt:
        update_cache: yes
    - name: update and upgrade all packages
      apt:
        name: "*"
        state: latest
    - name: install base apps
      apt:
        name:
          - ca-certificates
          - cmatrix
          - curl
          - flatpak
          - gnupg
          - htop
          - nala
          - neofetch
          - lsb-release
          - tmux
          - unzip
          - wget
          - zsh
        state: latest
    - name: change shell
      user:
        name: zyzyx
        shell: /bin/zsh
    - name: add ssh key
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
    - name: make git folder
      ansible.builtin.file:
        path: /home/zyzyx/git/
        owner: zyzyx
        group: zyzyx
        state: directory
        mode: "0770"
    - name: clone nerd-font
      ansible.builtin.git:
        repo: https://github.com/ryanoasis/nerd-fonts
        dest: /home/zyzyx/git/nerd-fonts/
        depth: 1
    - name: install nerd-fonts
      ansible.builtin.script:
        cmd: /home/zyzyx/git/nerd-fonts/install.sh
    - name: remove nerd-fonts
      ansible.builtin.file:
        path: /home/zyzyx/git/nerd-fonts/
        state: absent
    - name: clone Neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        dest: /home/zyzyx/git/
        depth: 1
    - name: install Neovim
      make:
        chdir: /home/zyzyx/git/
    - name: clone dotFiles
      ansible.builtin.git:
        repo: https://github.com/zyzyx159/dotFiles
        dest: /home/zyzyx/git/
        depth: 1
    - name: delete original dot files
      file:
        path: "{{ item }}"
        state: absent
        become: yes
      with_items:
        - ~/.config/kitty/
        - ~/.config/nvim/
        - ~/.config/nvim-writing/
        - ~/.config/custScripts/
        - ~/.config/starship.toml
        - ~/.config/terminator/
        - ~/.config/tmux/
        - ~/.zshrc
        - /etc/ssh/sshd_config
    - name: link dot files
      file:
        src: "{{item.path}}"
        dest: "{{item.dest}}"
        with_items:
          - ~/git/dotFiles/kitty/ ~/.config/kitty/
          - ~/git/dotFiles/nvim-programing/ ~/.config/nvim/
          - ~/git/dotFiles/nvim-writing/ ~/.config/nvim-writing/
          - ~/git/dotFiles/scripts/ ~.config/custScripts/
          - ~/git/dotFiles/starship/starship.toml ~/.config/starship.toml
          - ~/git/dotFiles/terminator ~/.config/terminator/
          - ~/git/dotFiles/tmux/ ~/.config/tmux/
          - ~/git/dotFiles/zsh/.zshrc ~/.zshrc
        owner: zyzyx
        group: zyzyx
        state: link
        mode: "740"
    - name: copy sshd_config file
      file:
        src: ~/git/dotFiles/ssh/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: find 16 fastest repositories
      ansible.builtin.shell: nala fetch --auto --fetches 16
      become: true
    - name: nala update
      ansible.builtin.shell: nala update
      become: true
