---
- hosts: all
  become: yes
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: update
      apt:
        update_cache: yes
    - name: update and upgrade all packages
      apt:
        name: "*"
        state: latest
    - name: install base apps
      apt:
        name:
          - ca-certificates
          - cmatrix
          - curl
          - flatpak
          - gnupg
          - htop
          - nala
          - neofetch
          - lsb-release
          - sudo
          - tmux
          - unzip
          - wget
          - zsh
        state: latest
    - name: change shell
      user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: make git folder
      ansible.builtin.file:
        path: /home/zyzyx/git/
        owner: zyzyx
        group: zyzyx
        mode: '1770'
    - name: clone nerd-font
      ansible.builtin.git:
        repo: https://github.com/ryanoasis/nerd-fonts
        dest: /home/zyzyx/git/
        depth: 1
    - name: install nerd-fonts
      ansible.builtin.script:
        cmd: /home/zyzyx/git/nerd-fonts/install.sh
    - name: remove nerd-fonts
      ansible.builtin.file:
        path: /home/zyzyx/git/nerd-fonts/
        state: absent
    - name: find 16 fastest repositories
      ansible.builtin.shell: nala fetch --auto --fetches 16
      become: true
    - name: nala update
      ansible.builtin.shell: nala update
      become: true
