---
- hosts: all
  become: yes
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: update
      apt:
        update_cache: yes
    - name: update and upgrade all packages
      apt:
        name: "*"
        state: latest
    - name: install base apps
      apt:
        name:
          - ca-certificates
          - cmatrix
          - curl
          - flatpak
          - gnupg
          - htop
          - nala
          - neofetch
          - lsb-release
          - sudo
          - tmux
          - unzip
          - wget
          - zsh
        state: latest
    - name: Download and unzip CascadiaCode.zip
      unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
        dest: /usr/share/fonts/truetype/CaskaydiaCove/
        remote_src: yes
    - name: change user shell to zsh
      user:
        name: zyzyx
        shell: /bin/zsh
    - name: change shell
      user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: copy .zshrc
      copy:
        src: Files/zshrc
        dest: /home/zyzyx/.zshrc
        owner: zyzyx
        group: zyzyx
        mode: 0740
    - name: find 16 fastest repositories
      ansible.builtin.shell: nala fetch --auto --fetches 16
      become: true
    - name: nala update
      ansible.builtin.shell: nala update
      become: true
