---

- hosts: all
  become: yes
  tasks:
  - name: update
    apt: 
      update_cache: yes
  - name: update and upgrade all packages
    apt:
      name: "*"
      state: latest
  - name: install base apps
    apt:
      name:
        - curl
        - cmatrix
        - htop
        - neofetch
        - ca-certificates
        - gnupg
        - lsb-release
        - zsh
        - zplug
        - wget
        - unzip
      state: latest
  - name: Make folders for Git projects
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - /home/zyzyx/Git
      - /home/zyzyx/Git/ohmyzsh 
      - /home/zyzyx/.poshthemes # owned by me
  - name: Download oh-my-zsh installer
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /home/zyzyx/Git/ohmyzsh/install.sh
  - name: Add execute permsions to scripts
    file:
      path: "{{ item }}"
      state: file
      owner: zyzyx
      group: zyzyx
      mode: u+rwx,g+rwx,o-rwx
    loop:
      - /home/zyzyx/Git/ohmyzsh/install.sh
  - name: Run oh-my-zsh installer
    become: yes
    become_user: zyzyx
    command: sh /home/zyzyx/Git/ohmyzsh/install.sh --unattended
  - name: Clone zsh autocomplete repository
    git:
      repo: https://github.com/marlonrichert/zsh-autocomplete.git
      dest: /home/zyzyx/.oh-my-zsh/custom/plugins/zsh-autocomplete
      clone: yes
      update: yes
  - name: Clone zsh suggestions repository
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/zyzyx/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      clone: yes
      update: yes
  - name: download oh-my-posh
    get_url:
      url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64
      dest: /usr/local/bin/oh-my-posh
  - name: add execute
    file:
      path: "{{ item }}"
      state: file
      mode: u+rwx,g+rx,o+rx
    loop:
      - /usr/local/bin/oh-my-posh
  - name: Download and unzip poshthemes
    unarchive: 
      src: https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip
      dest: /home/zyzyx/.poshthemes
      remote_src: yes
  - name: Download and unzip CascadiaCode.zip
    unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
      dest: /usr/share/fonts/truetype
      remote_src: yes
  - name: Change owner of files and folders
    file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: zyzyx
      group: zyzyx
      mode: 0740
    loop:
      - /home/zyzyx/Git
      - /home/zyzyx/.poshthemes
  - name: change shell
    user:
      name: zyzyx
      shell: /bin/zsh
      groups: wheel
      append: yes
  - name: copy bashrc
    copy:
      src: Files/bashrc
      dest: /home/zyzyx/.bashrc
      owner: zyzyx
      group: zyzyx
      mode: 0740
  - name: copy .zshrc
    copy:
      src: Files/zshrc
      dest: /home/zyzyx/.zshrc
      owner: zyzyx
      group: zyzyx
      mode: 0740
  - name: copy zyzyx.json
    copy:
      src: Files/zyzyx.json
      dest: /home/zyzyx/.poshthemes/zyzyx.omp.json
      owner: zyzyx
      group: zyzyx
      mode: 0740