---
- hosts: all
  vars:
    ssh_key_filename: ed25519_key
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: install base apps
      apt:
        name:
          - build-essential
          - ca-certificates
          - cmake
          - cmatrix
          - gettext
          - gnupg
          - htop
          - neofetch
          - lsb-release
          - lsd
          - sudo
          - tmux
          - unzip
          - zsh
        state: latest
    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: add user zyzyx
      ansible.builtin.user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: Create ~/.ssh
      ansible.builtin.file:
        path: /home/zyzyx/.ssh
        state: directory
        mode: '0710'
    - name: generate SSH key "{{ssh_key_filename}}"
      community.crypto.openssh_keypair:
        path: /home/zyzyx/.ssh/{{ssh_key_filename}}
        type: ed25519
        comment: Dstellm@gmail.com
    - name: GHPush echo
      ansible.builtin.debug:
        msg: "ghpush {{ lookup('ansible.builtin.file', '/home/zyzyx/.ssh/ed25519_key.pub') }} zyzyx@{{ansible_hostname}}"
    - name: add ssh key to authorised_keys
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
