---
- hosts: all
  become: yes
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: update
      apt:
        update_cache: yes
    - name: update and upgrade all packages
      apt:
        name: "*"
        state: latest
    - name: install base apps
      apt:
        name:
          - build-essential
          - ca-certificates
          - cmake
          - cmatrix
          - curl
          - gettext
          - gnupg
          - htop
          - nala
          - neofetch
          - lsb-release
          - lsd
          - tmux
          - unzip
          - wget
          - zsh
        state: latest
    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
