---
- name: "run local"
  hosts: localhost
  connection: local
  tasks:
    - name: change shell
      user:
        name: zyzyx
        shell: /bin/zsh
    - name: add ssh key
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
    - name: make git folder
      ansible.builtin.file:
        path: /home/zyzyx/git/
        owner: zyzyx
        group: zyzyx
        state: directory
        mode: "0770"
    - name: clone Neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        dest: /home/zyzyx/git/neovim
        depth: 1
    - name: install Neovim
      make:
        chdir: /home/zyzyx/git/neovim
    - name: clone dotFiles
      ansible.builtin.git:
        repo: https://github.com/zyzyx159/dotFiles
        dest: /home/zyzyx/git/dotFiles
        depth: 1
    - name: delete original dot files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~/.config/kitty/
        - ~/.config/nvim/
        - ~/.config/nvim-writing/
        - ~/.config/custScripts/
        - ~/.config/starship.toml
        - ~/.config/terminator/
        - ~/.config/tmux/
        - ~/.zshrc
    - name: link dot files
      file:
        src: "{{item.path}}"
        dest: "{{item.dest}}"
        with_items:
          - { path: ~/git/dotFiles/kitty/, dest: ~/.config/kitty/
          - ~/git/dotFiles/nvim-programing/ ~/.config/nvim/
          - ~/git/dotFiles/nvim-writing/ ~/.config/nvim-writing/
          - ~/git/dotFiles/scripts/ ~.config/custScripts/
          - ~/git/dotFiles/starship/starship.toml ~/.config/starship.toml
          - ~/git/dotFiles/terminator ~/.config/terminator/
          - ~/git/dotFiles/tmux/ ~/.config/tmux/
          - ~/git/dotFiles/zsh/.zshrc ~/.zshrc
        owner: zyzyx
        group: zyzyx
        state: link
        mode: "740"
